/* globals cpcBasic */

"use strict";

cpcBasic.addItem("", function () { /*
CPCBasic;B;16384;703;0;base64,AEASQD8BUUFeAK9BowBSQm0ANb//2P8RAL//KAARAEEAKAARAEEA2P8RAMT/3f8RAMT/IwARADwAIwARADwA3f8RAL//2P/v/7//KADv/0EAKADv/0EA2P/v/8T/3f/v/8T/IwDv/zwAIwDv/zwA3f/v/87/CgAHAM7/FAAHANP/GQAHAOz/GQAHAPH/FAAHAPH/BQAHAOz/AAAHAPH/+/8HAPH/7P8HAOz/5/8HANP/5/8HAM7/7P8HAM7/9v8HAN3/9v8HAN3/8f8HAOL/8f8HAOL/+/8HANb/+/8HANb/BQAHAOL/BQAHAOL/DwAHAN3/DwAHAN3/CgAHAPb/+/8HAPb/BQAHAAoABQAHAAoA+/8HAA8A5/8HAA8AGQAHAC0AGQAHADIAFAAHADIA7P8HAC0A5/8HAB4A8f8HAB4ADwAHACMADwAHACMA8f8HABAFAAECAwAFBAUGBwQFCAkKCwgFDA0ODwwCCAACDAQCDQUCCQECCgICDgYCDwcCCwMYEBESExQVFhcYGRobHB0eHyAhIiMkJSYQBScoKSonByssLS4vMCsFMTIzNDEbAAAAAAASAAEAAAAQAAIAAAAOAAMAAAAMAAQAAAAKAAUAAAAIAAYAAAAGAAcAAAAEAAgAAAACAAkAAAAAAAoAAAACAAsAAAAEAAwAAAAGAA0AAAAIAA4AAAAKAA8AAAAMABAAAAAOABEAAAAQABIAAAASABQAAAAQABYAAAAKABgAAAAGABoAAAACABwAAAAAAB4AAAACACAAAAAKACIAAAAQNgCAAYACgAOABIAFgAaAB4AIgAmACoALgAyADYAOgA+AEIARgBKAE4AUgBWAFoAXgBiAGYAagACAGYAYgBeAFoAVgBSAE4ASgBGAEIAPgA6ADYAMgAuACoAJgAiAB4AGgAWABIADgAKAAYAAgA==
*/ });
